### ISSUE TITLE
Kernel for RaspberryPi B?

### ISSUE THREAD

**Issue by francisbesset** [stevef1uk/docker_for_rpi#3]
Hello,
I have a RaspberryPi B with Raspbian.

I am interested to use Docker.
Do you have the possibility to build the kernel for the RaspberryPi B?

**Comment by stevef1uk** [comment]
Only the latest kernel is for the Raspberry Pi 2. All the others are for the Raspberry Pi B. If your follow my blogs (links in the main README) you should be able to built one yourself. The process is identical except the initial configuration of the kernels will be different I expect and what you do with the generated file is slightly different. I did notice this blog post so someone has made life very easy for you if you want to try docker on the RPI: http://blog.hypriot.com/heavily-armed-after-major-upgrade-raspberry-pi-with-docker-1-dot-5-0
